name: website
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Decentraland Command Line
        run: npm install -g decentraland@next
      - name: Create test scene 
        run: yes Y | dcl init
      - name: (temp) install decentraland-ecs PR
        run: npm install decentraland@ci
      - name: (temp) install @dcl/kernel PR
        run: npm install "https://sdk-team-cdn.decentraland.org/@dcl/kernel/branch/feat/export-out-of-root-folder/dcl-kernel-1.0.0-1175438210.commit-6a4bf8e.tgz"
      - name: Build export
        run: dcl export --skip-version-checks
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: export
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
